name: Organization hygiene

on:
  workflow_call:
    inputs:
      run_pre_commit:
        description: Run pre-commit when the caller has a configuration file.
        required: false
        default: true
        type: boolean

permissions:
  contents: read

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5.0.0
      - if: ${{ inputs.run_pre_commit && hashFiles('.pre-commit-config.yaml') != '' }}
        uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1

  gitleaks:
    runs-on: ubuntu-latest
    container:
      image: zricethezav/gitleaks@sha256:b109bc5f8f76a38196a3e413704fc5b9e3c32360bce4e4b603bd6f45b3721dbb # v8.30.1 linux/amd64
    steps:
      - uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5.0.0
      - run: gitleaks detect --no-git --redact --source .

  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5.0.0
      - run: >-
          docker run --rm -v "${GITHUB_WORKSPACE}:/workspace:ro" -w /workspace
          rhysd/actionlint@sha256:2ef3ed94025747bd876118bfcae405d13532a07904d5ee0d70948110ef32f71d
          -color